#!/usr/bin/env python3
import time as t
import colors as c
import classes as cl
import town
import load

logo='''
 _______  _        _______           _______ 
(  ___  )( \      (  ____ )|\     /|(  ___  )
| (   ) || (      | (    )|| )   ( || (   ) |
| (___) || |      | (____)|| (___) || (___) |
|  ___  || |      |  _____)|  ___  ||  ___  |
| (   ) || |      | (      | (   ) || (   ) |
| )   ( || (____/\| )      | )   ( || )   ( |
|/     \|(_______/|/       |/     \||/     \|
                                             
 _______           _______  _______ _________
(  ___  )|\     /|(  ____ \(  ____ \\__   __/
| (   ) || )   ( || (    \/| (    \/   ) (   
| |   | || |   | || (__    | (_____    | |   
| |   | || |   | ||  __)   (_____  )   | |  
| | /\| || |   | || (            ) |   | |   
| (_\ \ || (___) || (____/\/\____) |   | |   
(____\/_)(_______)(_______/\_______)   )_(   

                            (BETA Ver 1.0)
'''

def run():
    print(c.clear)
    print(c.yellow+str("Hello! And welcome to...."))
    t.sleep(1)
    print(c.random_color()+logo)
    t.sleep(1)
    print()
    print()
    neworload()

def neworload():
    qws=input(c.yellow+"Do you want to start a new game? Or load a save file?"+c.reset+" (1), (2) >>>"+c.violet).strip()
    if qws=="1":
        qwa=input(c.yellow+"Are you sure? Any old save file will be deleted."+c.reset+" (Y/N) >>>"+c.violet).strip().lower()
        if qwa=="y":
            cl.Player=cl.Lost
            nameask()
        elif qwa=="n":
            neworload()
        else:
            neworload()
    elif qws=="2":
        print(c.yellow+"Okay! Here's your stats.")
        load.load_game()
        cl.show_player()
        qwz=input(c.yellow+"Are you sure you want to load this?"+c.reset+" (Y/N) >>>"+c.violet).strip().lower()
        if qwz=="y":
            town.hub()
        elif qwz=="n":
            neworload()
        else:
            print(c.yellow+"I don't understand... type Y for yes and N for no.")
            t.sleep(1.5)
            neworload()
    else:
        print(c.yellow+"I don't understand... type 1 for a save file, and 2 for loading a game.")
        t.sleep(1.5)
        neworload()

def intro():
    print(c.clear)
    print("You awake.")
    t.sleep(1)
    print("You look around.")
    t.sleep(1)
    print("You are lying down on your back in the woods.")
    t.sleep(2)
    print("This is not your cozy bed you fell asleep in last night.")
    t.sleep(2)
    print("You're lost.")
    t.sleep(1)
    print("You lift yourself off the ground.")
    t.sleep(2)
    print("As you look in the distance, you see a small town.")
    t.sleep(2)
    input("Looking for answers, you head to the town. [Press enter]")
    town.hub()

def nameask():
    name_question=input(c.yellow+"What is your name? "+c.reset+ ">>>"+c.violet).strip().title()
    confirm=input(c.yellow+"Oh, so your name is "+c.blue+name_question+c.yellow+"?"+c.reset+"(Y/N) >>>"+c.violet).strip().lower()
    if confirm=="y":
        cl.Player.name=name_question
        input(c.yellow+"Okay "+c.blue+cl.Player.name+c.yellow+", your adventure is about to start. Press enter to start!")
        cl.Player.gold+=100
        intro()
    elif confirm=="n":
        nameask()
    else:
        print("I don't understand... type Y for yes and N for no.")
        t.sleep(1.5)
        nameask()

if __name__=='__main__':
    run()
